set -euo pipefail


ENV_DIR="/root/infrastructure/consulpam/production"
mkdir -p "$ENV_DIR"

: "${DB_PASSWORD:?DB_PASSWORD não definida}"
: "${DB_USER:?DB_USER não definida}"
: "${PORT:? PORT não definido}"
: "${DB_NAME:?DB_NAME não definida}"
: "${DOCKERHUB_USERNAME:?DOCKERHUB_USERNAME não definida}"
: "${REFRESH_TOKEN:?REFRESH_TOKEN não definido}"
: "${REFRESH_EXPIRE:?REFRESH_EXPIRE não definido}"
: "${RESET_KEY:?RESET_KEY não definido}"
: "${RESET_EXPIRE:?RESET_EXPIRE não definido}"
: "${UPLOAD_DIR_PATH:?UPLOAD_DIR_PATH não definida}"
: "${INVITE_TOKEN:?INVITE_TOKEN não definida}"
: "${RABBITMQ_DEFAULT_USER:?RABBITMQ_DEFAULT_USER não definido}"
: "${RABBITMQ_DEFAULT_PASS:?RABBITMQ_DEFAULT_PASS não definida}"
: "${ACCESS_TOKEN:?ACCESS_TOKEN não definida}"
: "${ACCESS_EXPIRE:?ACCESS_EXPIRE não definida}"
: "${GITHUB_SHA:?GITHUB_SHA não definida}"
: "${UPLOAD_PATH:?UPLOAD_PATH não definido}"



cat <<EOF > "$ENV_DIR/.env.prod"
DB_PASSWORD=$DB_PASSWORD
DB_USER=$DB_USER
DB_NAME=$DB_NAME
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@postgres:5432/$DB_NAME
PORT=$PORT
ACCESS_TOKEN=$ACCESS_TOKEN
REFRESH_TOKEN=$REFRESH_TOKEN
REFRESH_EXPIRE=$REFRESH_EXPIRE
ACCESS_EXPIRE=$ACCESS_EXPIRE
RESET_KEY=$RESET_KEY
RESET_EXPIRE=$RESET_EXPIRE
UPLOAD_DIR_PATH=$UPLOAD_DIR_PATH
INVITE_TOKEN=$INVITE_TOKEN
URL_RABBITMQ=amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@rabbitmq:5672
GITHUB_SHA=$GITHUB_SHA
UPLOAD_PATH=$UPLOAD_PATH
EOF

cat <<EOF > "$ENV_DIR/.env.compose"
DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
POSTGRES_PASSWORD=$DB_PASSWORD
EOF
cat <<EOF > "$ENV_DIR/.env.rabbitmq_prod"
RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS

EOF

chmod 600 "$ENV_DIR"/.env.*

echo "🧩 Arquivos .env gerados"
